package com.sohu.article.dao;

import com.sohu.article.model.ArticleEntity;
import com.sohu.article.model.ArticleEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int countByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int deleteByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int insert(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int insertSelective(ArticleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    List<ArticleEntity> selectByExampleWithBLOBs(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    List<ArticleEntity> selectByExample(ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Dec 01 17:58:08 CST 2018
     */
    int updateByExample(@Param("record") ArticleEntity record, @Param("example") ArticleEntityExample example);
}