package com.sohu.article.dao;

import com.sohu.article.model.CoverWishesEntity;
import com.sohu.article.model.CoverWishesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoverWishesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    long countByExample(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int deleteByExample(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int deleteByPrimaryKey(Integer wishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int insert(CoverWishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int insertSelective(CoverWishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverWishesEntity selectOneByExample(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverWishesEntity selectOneByExampleSelective(@Param("example") CoverWishesEntityExample example, @Param("selective") CoverWishesEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverWishesEntity selectOneByExampleWithBLOBs(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CoverWishesEntity> selectByExampleSelective(@Param("example") CoverWishesEntityExample example, @Param("selective") CoverWishesEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    List<CoverWishesEntity> selectByExampleWithBLOBs(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    List<CoverWishesEntity> selectByExample(CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverWishesEntity selectByPrimaryKeySelective(@Param("wishId") Integer wishId, @Param("selective") CoverWishesEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    CoverWishesEntity selectByPrimaryKey(Integer wishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoverWishesEntity record, @Param("example") CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CoverWishesEntity record, @Param("example") CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByExample(@Param("record") CoverWishesEntity record, @Param("example") CoverWishesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByPrimaryKeySelective(CoverWishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CoverWishesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_wishes
     *
     * @mbg.generated Mon Jan 07 16:31:30 CST 2019
     */
    int updateByPrimaryKey(CoverWishesEntity record);
}