package com.sohu.article.dao;

import com.sohu.article.model.CoverShareEntity;
import com.sohu.article.model.CoverShareEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoverShareEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    long countByExample(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int deleteByExample(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int deleteByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int insert(CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int insertSelective(CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverShareEntity selectOneByExample(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverShareEntity selectOneByExampleSelective(@Param("example") CoverShareEntityExample example, @Param("selective") CoverShareEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverShareEntity selectOneByExampleWithBLOBs(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CoverShareEntity> selectByExampleSelective(@Param("example") CoverShareEntityExample example, @Param("selective") CoverShareEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    List<CoverShareEntity> selectByExampleWithBLOBs(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    List<CoverShareEntity> selectByExample(CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverShareEntity selectByPrimaryKeySelective(@Param("shareId") Integer shareId, @Param("selective") CoverShareEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    CoverShareEntity selectByPrimaryKey(Integer shareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleWithBLOBs(@Param("version") Integer version, @Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByExample(@Param("record") CoverShareEntity record, @Param("example") CoverShareEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByPrimaryKeySelective(CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeyWithBLOBs(@Param("version") Integer version, @Param("record") CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CoverShareEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    int updateByPrimaryKey(CoverShareEntity record);
}