package com.sohu.article.dao;

import com.sohu.article.model.CoverCommentEntity;
import com.sohu.article.model.CoverCommentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoverCommentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    long countByExample(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int deleteByExample(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int insert(CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int insertSelective(CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverCommentEntity selectOneByExample(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverCommentEntity selectOneByExampleSelective(@Param("example") CoverCommentEntityExample example, @Param("selective") CoverCommentEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverCommentEntity selectOneByExampleWithBLOBs(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CoverCommentEntity> selectByExampleSelective(@Param("example") CoverCommentEntityExample example, @Param("selective") CoverCommentEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    List<CoverCommentEntity> selectByExampleWithBLOBs(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    List<CoverCommentEntity> selectByExample(CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CoverCommentEntity selectByPrimaryKeySelective(@Param("commentId") Integer commentId, @Param("selective") CoverCommentEntity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    CoverCommentEntity selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleWithBLOBs(@Param("version") Integer version, @Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByExample(@Param("record") CoverCommentEntity record, @Param("example") CoverCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByPrimaryKeySelective(CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByPrimaryKeyWithBLOBs(@Param("version") Integer version, @Param("record") CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CoverCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    int updateByPrimaryKey(CoverCommentEntity record);
}