package com.sohu.article.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

@ApiModel(value="com.sohu.article.model.CoverImgEntity")
public class CoverImgEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_img.cover_id
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @ApiModelProperty(value="coverId封面id")
    private Integer coverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_img.img_url
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @ApiModelProperty(value="imgUrl封面url")
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_img.zan_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @ApiModelProperty(value="zanNums点赞数")
    private Integer zanNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_img.comment_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @ApiModelProperty(value="commentNums评论数")
    private Integer commentNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_img.version
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @ApiModelProperty(value="version乐观锁")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_img
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_img.cover_id
     *
     * @return the value of cover_img.cover_id
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public Integer getCoverId() {
        return coverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_img.cover_id
     *
     * @param coverId the value for cover_img.cover_id
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public void setCoverId(Integer coverId) {
        this.coverId = coverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_img.img_url
     *
     * @return the value of cover_img.img_url
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_img.img_url
     *
     * @param imgUrl the value for cover_img.img_url
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_img.zan_nums
     *
     * @return the value of cover_img.zan_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public Integer getZanNums() {
        return zanNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_img.zan_nums
     *
     * @param zanNums the value for cover_img.zan_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public void setZanNums(Integer zanNums) {
        this.zanNums = zanNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_img.comment_nums
     *
     * @return the value of cover_img.comment_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public Integer getCommentNums() {
        return commentNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_img.comment_nums
     *
     * @param commentNums the value for cover_img.comment_nums
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public void setCommentNums(Integer commentNums) {
        this.commentNums = commentNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_img.version
     *
     * @return the value of cover_img.version
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_img.version
     *
     * @param version the value for cover_img.version
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coverId=").append(coverId);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", zanNums=").append(zanNums);
        sb.append(", commentNums=").append(commentNums);
        sb.append(", version=").append(version);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoverImgEntity other = (CoverImgEntity) that;
        return (this.getCoverId() == null ? other.getCoverId() == null : this.getCoverId().equals(other.getCoverId()))
            && (this.getImgUrl() == null ? other.getImgUrl() == null : this.getImgUrl().equals(other.getImgUrl()))
            && (this.getZanNums() == null ? other.getZanNums() == null : this.getZanNums().equals(other.getZanNums()))
            && (this.getCommentNums() == null ? other.getCommentNums() == null : this.getCommentNums().equals(other.getCommentNums()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Wed Jan 02 18:29:22 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCoverId() == null) ? 0 : getCoverId().hashCode());
        result = prime * result + ((getImgUrl() == null) ? 0 : getImgUrl().hashCode());
        result = prime * result + ((getZanNums() == null) ? 0 : getZanNums().hashCode());
        result = prime * result + ((getCommentNums() == null) ? 0 : getCommentNums().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cover_img
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        coverId("cover_id", "coverId", "INTEGER", false),
        imgUrl("img_url", "imgUrl", "VARCHAR", false),
        zanNums("zan_nums", "zanNums", "INTEGER", false),
        commentNums("comment_nums", "commentNums", "INTEGER", false),
        version("version", "version", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}