package com.sohu.article.model;

import java.util.ArrayList;
import java.util.List;

public class CoverImgEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public CoverImgEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CoverImgEntityExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CoverImgEntityExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCoverIdIsNull() {
            addCriterion("cover_id is null");
            return (Criteria) this;
        }

        public Criteria andCoverIdIsNotNull() {
            addCriterion("cover_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoverIdEqualTo(Integer value) {
            addCriterion("cover_id =", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdNotEqualTo(Integer value) {
            addCriterion("cover_id <>", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdGreaterThan(Integer value) {
            addCriterion("cover_id >", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cover_id >=", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdLessThan(Integer value) {
            addCriterion("cover_id <", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdLessThanOrEqualTo(Integer value) {
            addCriterion("cover_id <=", value, "coverId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCoverIdLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("cover_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCoverIdIn(List<Integer> values) {
            addCriterion("cover_id in", values, "coverId");
            return (Criteria) this;
        }

        public Criteria andCoverIdNotIn(List<Integer> values) {
            addCriterion("cover_id not in", values, "coverId");
            return (Criteria) this;
        }

        public Criteria andCoverIdBetween(Integer value1, Integer value2) {
            addCriterion("cover_id between", value1, value2, "coverId");
            return (Criteria) this;
        }

        public Criteria andCoverIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cover_id not between", value1, value2, "coverId");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return (Criteria) this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgUrlLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlIn(List<String> values) {
            addCriterion("img_url in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotIn(List<String> values) {
            addCriterion("img_url not in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andZanNumsIsNull() {
            addCriterion("zan_nums is null");
            return (Criteria) this;
        }

        public Criteria andZanNumsIsNotNull() {
            addCriterion("zan_nums is not null");
            return (Criteria) this;
        }

        public Criteria andZanNumsEqualTo(Integer value) {
            addCriterion("zan_nums =", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsNotEqualTo(Integer value) {
            addCriterion("zan_nums <>", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsGreaterThan(Integer value) {
            addCriterion("zan_nums >", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("zan_nums >=", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsLessThan(Integer value) {
            addCriterion("zan_nums <", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsLessThanOrEqualTo(Integer value) {
            addCriterion("zan_nums <=", value, "zanNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andZanNumsLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("zan_nums <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZanNumsIn(List<Integer> values) {
            addCriterion("zan_nums in", values, "zanNums");
            return (Criteria) this;
        }

        public Criteria andZanNumsNotIn(List<Integer> values) {
            addCriterion("zan_nums not in", values, "zanNums");
            return (Criteria) this;
        }

        public Criteria andZanNumsBetween(Integer value1, Integer value2) {
            addCriterion("zan_nums between", value1, value2, "zanNums");
            return (Criteria) this;
        }

        public Criteria andZanNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("zan_nums not between", value1, value2, "zanNums");
            return (Criteria) this;
        }

        public Criteria andCommentNumsIsNull() {
            addCriterion("comment_nums is null");
            return (Criteria) this;
        }

        public Criteria andCommentNumsIsNotNull() {
            addCriterion("comment_nums is not null");
            return (Criteria) this;
        }

        public Criteria andCommentNumsEqualTo(Integer value) {
            addCriterion("comment_nums =", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsNotEqualTo(Integer value) {
            addCriterion("comment_nums <>", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsGreaterThan(Integer value) {
            addCriterion("comment_nums >", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_nums >=", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsLessThan(Integer value) {
            addCriterion("comment_nums <", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsLessThanOrEqualTo(Integer value) {
            addCriterion("comment_nums <=", value, "commentNums");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCommentNumsLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("comment_nums <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCommentNumsIn(List<Integer> values) {
            addCriterion("comment_nums in", values, "commentNums");
            return (Criteria) this;
        }

        public Criteria andCommentNumsNotIn(List<Integer> values) {
            addCriterion("comment_nums not in", values, "commentNums");
            return (Criteria) this;
        }

        public Criteria andCommentNumsBetween(Integer value1, Integer value2) {
            addCriterion("comment_nums between", value1, value2, "commentNums");
            return (Criteria) this;
        }

        public Criteria andCommentNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_nums not between", value1, value2, "commentNums");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andVersionLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("version <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andWishTypeIsNull() {
            addCriterion("wish_type is null");
            return (Criteria) this;
        }

        public Criteria andWishTypeIsNotNull() {
            addCriterion("wish_type is not null");
            return (Criteria) this;
        }

        public Criteria andWishTypeEqualTo(String value) {
            addCriterion("wish_type =", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeNotEqualTo(String value) {
            addCriterion("wish_type <>", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeGreaterThan(String value) {
            addCriterion("wish_type >", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeGreaterThanOrEqualTo(String value) {
            addCriterion("wish_type >=", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeLessThan(String value) {
            addCriterion("wish_type <", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeLessThanOrEqualTo(String value) {
            addCriterion("wish_type <=", value, "wishType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andWishTypeLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("wish_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWishTypeLike(String value) {
            addCriterion("wish_type like", value, "wishType");
            return (Criteria) this;
        }

        public Criteria andWishTypeNotLike(String value) {
            addCriterion("wish_type not like", value, "wishType");
            return (Criteria) this;
        }

        public Criteria andWishTypeIn(List<String> values) {
            addCriterion("wish_type in", values, "wishType");
            return (Criteria) this;
        }

        public Criteria andWishTypeNotIn(List<String> values) {
            addCriterion("wish_type not in", values, "wishType");
            return (Criteria) this;
        }

        public Criteria andWishTypeBetween(String value1, String value2) {
            addCriterion("wish_type between", value1, value2, "wishType");
            return (Criteria) this;
        }

        public Criteria andWishTypeNotBetween(String value1, String value2) {
            addCriterion("wish_type not between", value1, value2, "wishType");
            return (Criteria) this;
        }

        public Criteria andImgTypeIsNull() {
            addCriterion("img_type is null");
            return (Criteria) this;
        }

        public Criteria andImgTypeIsNotNull() {
            addCriterion("img_type is not null");
            return (Criteria) this;
        }

        public Criteria andImgTypeEqualTo(String value) {
            addCriterion("img_type =", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeNotEqualTo(String value) {
            addCriterion("img_type <>", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeNotEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeGreaterThan(String value) {
            addCriterion("img_type >", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeGreaterThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("img_type >=", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeGreaterThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeLessThan(String value) {
            addCriterion("img_type <", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeLessThanColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeLessThanOrEqualTo(String value) {
            addCriterion("img_type <=", value, "imgType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andImgTypeLessThanOrEqualToColumn(CoverImgEntity.Column column) {
            addCriterion(new StringBuilder("img_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andImgTypeLike(String value) {
            addCriterion("img_type like", value, "imgType");
            return (Criteria) this;
        }

        public Criteria andImgTypeNotLike(String value) {
            addCriterion("img_type not like", value, "imgType");
            return (Criteria) this;
        }

        public Criteria andImgTypeIn(List<String> values) {
            addCriterion("img_type in", values, "imgType");
            return (Criteria) this;
        }

        public Criteria andImgTypeNotIn(List<String> values) {
            addCriterion("img_type not in", values, "imgType");
            return (Criteria) this;
        }

        public Criteria andImgTypeBetween(String value1, String value2) {
            addCriterion("img_type between", value1, value2, "imgType");
            return (Criteria) this;
        }

        public Criteria andImgTypeNotBetween(String value1, String value2) {
            addCriterion("img_type not between", value1, value2, "imgType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cover_img
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 22 11:25:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private CoverImgEntityExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(CoverImgEntityExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public CoverImgEntityExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table cover_img
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table cover_img
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cover_img
     *
     * @mbg.generated Tue Jan 22 11:25:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}