package com.sohu.article.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

@ApiModel(value="com.sohu.article.model.CoverCommentEntity")
public class CoverCommentEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.comment_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="commentId评论id")
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.comment_time
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="commentTime评论时间")
    private Date commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.user_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="userId评论客户id")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.cover_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="coverId评论的贺卡id")
    private Integer coverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.version
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="version乐观锁")
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_comment.comment_content
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @ApiModelProperty(value="commentContent评论内容")
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.comment_id
     *
     * @return the value of cover_comment.comment_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.comment_id
     *
     * @param commentId the value for cover_comment.comment_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.comment_time
     *
     * @return the value of cover_comment.comment_time
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.comment_time
     *
     * @param commentTime the value for cover_comment.comment_time
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.user_id
     *
     * @return the value of cover_comment.user_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.user_id
     *
     * @param userId the value for cover_comment.user_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.cover_id
     *
     * @return the value of cover_comment.cover_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public Integer getCoverId() {
        return coverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.cover_id
     *
     * @param coverId the value for cover_comment.cover_id
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setCoverId(Integer coverId) {
        this.coverId = coverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.version
     *
     * @return the value of cover_comment.version
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.version
     *
     * @param version the value for cover_comment.version
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_comment.comment_content
     *
     * @return the value of cover_comment.comment_content
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_comment.comment_content
     *
     * @param commentContent the value for cover_comment.comment_content
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", userId=").append(userId);
        sb.append(", coverId=").append(coverId);
        sb.append(", version=").append(version);
        sb.append(", commentContent=").append(commentContent);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoverCommentEntity other = (CoverCommentEntity) that;
        return (this.getCommentId() == null ? other.getCommentId() == null : this.getCommentId().equals(other.getCommentId()))
            && (this.getCommentTime() == null ? other.getCommentTime() == null : this.getCommentTime().equals(other.getCommentTime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCoverId() == null ? other.getCoverId() == null : this.getCoverId().equals(other.getCoverId()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getCommentContent() == null ? other.getCommentContent() == null : this.getCommentContent().equals(other.getCommentContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_comment
     *
     * @mbg.generated Wed Jan 02 18:28:34 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCommentId() == null) ? 0 : getCommentId().hashCode());
        result = prime * result + ((getCommentTime() == null) ? 0 : getCommentTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCoverId() == null) ? 0 : getCoverId().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getCommentContent() == null) ? 0 : getCommentContent().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cover_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        commentId("comment_id", "commentId", "INTEGER", false),
        commentTime("comment_time", "commentTime", "DATE", false),
        userId("user_id", "userId", "INTEGER", false),
        coverId("cover_id", "coverId", "INTEGER", false),
        version("version", "version", "INTEGER", false),
        commentContent("comment_content", "commentContent", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}