package com.sohu.article.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

@ApiModel(value="com.sohu.article.model.CoverShareEntity")
public class CoverShareEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.share_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="shareId分享id")
    private Integer shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.music_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="musicId歌曲id")
    private Integer musicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.user_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="userId用户id")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.img_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="imgId贺词背景图片id")
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.wish_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="wishId贺词表主键id")
    private Integer wishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.share_date
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="shareDate分享时间")
    private Date shareDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.version
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="version乐观锁")
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_share.wish_word
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @ApiModelProperty(value="wishWord贺词")
    private String wishWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.share_id
     *
     * @return the value of cover_share.share_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.share_id
     *
     * @param shareId the value for cover_share.share_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.music_id
     *
     * @return the value of cover_share.music_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getMusicId() {
        return musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.music_id
     *
     * @param musicId the value for cover_share.music_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setMusicId(Integer musicId) {
        this.musicId = musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.user_id
     *
     * @return the value of cover_share.user_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.user_id
     *
     * @param userId the value for cover_share.user_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.img_id
     *
     * @return the value of cover_share.img_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.img_id
     *
     * @param imgId the value for cover_share.img_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.wish_id
     *
     * @return the value of cover_share.wish_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getWishId() {
        return wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.wish_id
     *
     * @param wishId the value for cover_share.wish_id
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setWishId(Integer wishId) {
        this.wishId = wishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.share_date
     *
     * @return the value of cover_share.share_date
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Date getShareDate() {
        return shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.share_date
     *
     * @param shareDate the value for cover_share.share_date
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setShareDate(Date shareDate) {
        this.shareDate = shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.version
     *
     * @return the value of cover_share.version
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.version
     *
     * @param version the value for cover_share.version
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_share.wish_word
     *
     * @return the value of cover_share.wish_word
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public String getWishWord() {
        return wishWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_share.wish_word
     *
     * @param wishWord the value for cover_share.wish_word
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    public void setWishWord(String wishWord) {
        this.wishWord = wishWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shareId=").append(shareId);
        sb.append(", musicId=").append(musicId);
        sb.append(", userId=").append(userId);
        sb.append(", imgId=").append(imgId);
        sb.append(", wishId=").append(wishId);
        sb.append(", shareDate=").append(shareDate);
        sb.append(", version=").append(version);
        sb.append(", wishWord=").append(wishWord);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoverShareEntity other = (CoverShareEntity) that;
        return (this.getShareId() == null ? other.getShareId() == null : this.getShareId().equals(other.getShareId()))
            && (this.getMusicId() == null ? other.getMusicId() == null : this.getMusicId().equals(other.getMusicId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getImgId() == null ? other.getImgId() == null : this.getImgId().equals(other.getImgId()))
            && (this.getWishId() == null ? other.getWishId() == null : this.getWishId().equals(other.getWishId()))
            && (this.getShareDate() == null ? other.getShareDate() == null : this.getShareDate().equals(other.getShareDate()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getWishWord() == null ? other.getWishWord() == null : this.getWishWord().equals(other.getWishWord()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_share
     *
     * @mbg.generated Thu Jan 24 14:16:01 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShareId() == null) ? 0 : getShareId().hashCode());
        result = prime * result + ((getMusicId() == null) ? 0 : getMusicId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getImgId() == null) ? 0 : getImgId().hashCode());
        result = prime * result + ((getWishId() == null) ? 0 : getWishId().hashCode());
        result = prime * result + ((getShareDate() == null) ? 0 : getShareDate().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getWishWord() == null) ? 0 : getWishWord().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cover_share
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        shareId("share_id", "shareId", "INTEGER", false),
        musicId("music_id", "musicId", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        imgId("img_id", "imgId", "INTEGER", false),
        wishId("wish_id", "wishId", "INTEGER", false),
        shareDate("share_date", "shareDate", "DATE", false),
        version("version", "version", "INTEGER", false),
        wishWord("wish_word", "wishWord", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_share
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}