package com.sohu.article.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

@ApiModel(value="com.sohu.article.model.CoverMusicEntity")
public class CoverMusicEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_music.music_id
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @ApiModelProperty(value="musicId歌曲id")
    private Integer musicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_music.music_url
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @ApiModelProperty(value="musicUrl歌曲url")
    private String musicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_music.music_name
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @ApiModelProperty(value="musicName歌曲名")
    private String musicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_music.music_author
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @ApiModelProperty(value="musicAuthor歌曲作者")
    private String musicAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cover_music.version
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @ApiModelProperty(value="version乐观锁")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cover_music
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_music.music_id
     *
     * @return the value of cover_music.music_id
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public Integer getMusicId() {
        return musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_music.music_id
     *
     * @param musicId the value for cover_music.music_id
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public void setMusicId(Integer musicId) {
        this.musicId = musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_music.music_url
     *
     * @return the value of cover_music.music_url
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public String getMusicUrl() {
        return musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_music.music_url
     *
     * @param musicUrl the value for cover_music.music_url
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public void setMusicUrl(String musicUrl) {
        this.musicUrl = musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_music.music_name
     *
     * @return the value of cover_music.music_name
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_music.music_name
     *
     * @param musicName the value for cover_music.music_name
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_music.music_author
     *
     * @return the value of cover_music.music_author
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public String getMusicAuthor() {
        return musicAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_music.music_author
     *
     * @param musicAuthor the value for cover_music.music_author
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public void setMusicAuthor(String musicAuthor) {
        this.musicAuthor = musicAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cover_music.version
     *
     * @return the value of cover_music.version
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cover_music.version
     *
     * @param version the value for cover_music.version
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_music
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", musicId=").append(musicId);
        sb.append(", musicUrl=").append(musicUrl);
        sb.append(", musicName=").append(musicName);
        sb.append(", musicAuthor=").append(musicAuthor);
        sb.append(", version=").append(version);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_music
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoverMusicEntity other = (CoverMusicEntity) that;
        return (this.getMusicId() == null ? other.getMusicId() == null : this.getMusicId().equals(other.getMusicId()))
            && (this.getMusicUrl() == null ? other.getMusicUrl() == null : this.getMusicUrl().equals(other.getMusicUrl()))
            && (this.getMusicName() == null ? other.getMusicName() == null : this.getMusicName().equals(other.getMusicName()))
            && (this.getMusicAuthor() == null ? other.getMusicAuthor() == null : this.getMusicAuthor().equals(other.getMusicAuthor()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cover_music
     *
     * @mbg.generated Thu Jan 24 10:31:33 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMusicId() == null) ? 0 : getMusicId().hashCode());
        result = prime * result + ((getMusicUrl() == null) ? 0 : getMusicUrl().hashCode());
        result = prime * result + ((getMusicName() == null) ? 0 : getMusicName().hashCode());
        result = prime * result + ((getMusicAuthor() == null) ? 0 : getMusicAuthor().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cover_music
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        musicId("music_id", "musicId", "INTEGER", false),
        musicUrl("music_url", "musicUrl", "VARCHAR", false),
        musicName("music_name", "musicName", "VARCHAR", false),
        musicAuthor("music_author", "musicAuthor", "VARCHAR", false),
        version("version", "version", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cover_music
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}